// === MATERIALS — alle Material-Definitionen ===
// Exportiert als window.INSEL_MATERIALS (Vanilla JS, kein Build-Tool)

window.INSEL_MATERIALS = {
    // === DIE 5 ELEMENTE (五行 Wu Xing) ===
    metal:    { emoji: '⬜', label: 'Metall',   color: '#C0C0C0', border: '#A0A0A0' },
    wood:     { emoji: '🟩', label: 'Holz',     color: '#2E7D32', border: '#1B5E20' },
    fire:     { emoji: '🟥', label: 'Feuer',    color: '#D32F2F', border: '#B71C1C' },
    water:    { emoji: '⬛', label: 'Wasser',   color: '#1A1A2E', border: '#0D0D1A' },
    earth:    { emoji: '🟨', label: 'Erde',     color: '#F5C800', border: '#C8A300' },
    // === ABGELEITETE MATERIALIEN ===
    stone:    { emoji: '🧱', label: 'Stein',    color: '#95A5A6', border: '#7F8C8D' },
    glass:    { emoji: '🪟', label: 'Glas',     color: '#AED6F1', border: '#85C1E9' },
    plant:    { emoji: '🌿', label: 'Pflanze',  color: '#52BE80', border: '#27AE60' },
    sapling:  { emoji: '🌱', label: 'Setzling', color: '#7DCEA0', border: '#52BE80' },
    small_tree: { emoji: '🌲', label: 'Kleiner Baum', color: '#229954', border: '#1E8449' },
    tree:     { emoji: '🌳', label: 'Baum',     color: '#1E8449', border: '#196F3D' },
    flower:   { emoji: '🌸', label: 'Blume',    color: '#F1948A', border: '#E74C3C' },
    door:     { emoji: '🚪', label: 'Tür',      color: '#6E3B1A', border: '#4A2510' },
    roof:     { emoji: '🏠', label: 'Dach',     color: '#E74C3C', border: '#C0392B' },
    lamp:     { emoji: '💡', label: 'Lampe',    color: '#F9E79F', border: '#F1C40F' },
    sand:     { emoji: '⬜', label: 'Sand',     color: '#F5DEB3', border: '#DCC89E' },
    path:     { emoji: '🟫', label: 'Weg',      color: '#A0522D', border: '#8B4513' },
    fence:    { emoji: '🏗️', label: 'Zaun',     color: '#C4A265', border: '#A08040' },
    boat:     { emoji: '⛵', label: 'Boot',     color: '#5DADE2', border: '#2E86C1' },
    fish:     { emoji: '🐟', label: 'Fisch',    color: '#48C9B0', border: '#1ABC9C' },
    fountain: { emoji: '⛲', label: 'Brunnen',  color: '#7FB3D8', border: '#5499C7' },
    flag:     { emoji: '🚩', label: 'Flagge',   color: '#E74C3C', border: '#B03A2E' },
    bridge:   { emoji: '🌉', label: 'Brücke',   color: '#B7950B', border: '#9A7D0A' },
    cactus:   { emoji: '🌵', label: 'Kaktus',   color: '#28B463', border: '#1D8348' },
    mushroom: { emoji: '🍄', label: 'Pilz',     color: '#E59866', border: '#CA6F1E' },
    planks:   { emoji: '🪵', label: 'Bretter',  color: '#C19A6B', border: '#A0784A' },
    window_pane: { emoji: '🪟', label: 'Fenster', color: '#D4EFFC', border: '#AED6F1' },
    // === MAGISCHE ARTEFAKTE ===
    steam:    { emoji: '💨', label: 'Dampf',    color: '#D5D8DC', border: '#AEB6BF' },
    ice:      { emoji: '🧊', label: 'Eis',      color: '#D6EAF8', border: '#AED6F1' },
    snow:     { emoji: '❄️', label: 'Schnee',   color: '#EBF5FB', border: '#D6EAF8' },
    cloud:    { emoji: '☁️', label: 'Wolke',    color: '#F2F4F4', border: '#D5D8DC' },
    rain:     { emoji: '🌧️', label: 'Regen',   color: '#85C1E9', border: '#5DADE2' },
    rainbow:  { emoji: '🌈', label: 'Regenbogen', color: '#F9E79F', border: '#F4D03F' },
    sun:      { emoji: '☀️', label: 'Sonne',    color: '#F9E79F', border: '#F1C40F' },
    star:     { emoji: '⭐', label: 'Stern',    color: '#F9E79F', border: '#F4D03F' },
    moon:     { emoji: '🌙', label: 'Mond',     color: '#F7DC6F', border: '#F1C40F' },
    lightning:{ emoji: '⚡', label: 'Blitz',    color: '#F7DC6F', border: '#F4D03F' },
    volcano:  { emoji: '🌋', label: 'Vulkan',   color: '#E74C3C', border: '#C0392B' },
    mountain: { emoji: '🏔️', label: 'Berg',    color: '#95A5A6', border: '#7F8C8D' },
    diamond:  { emoji: '💎', label: 'Diamant',  color: '#AED6F1', border: '#85C1E9' },
    sword:    { emoji: '⚔️', label: 'Schwert',  color: '#BDC3C7', border: '#95A5A6' },
    shield:   { emoji: '🛡️', label: 'Schild',  color: '#F0B27A', border: '#E59866' },
    crown:    { emoji: '👑', label: 'Krone',    color: '#F9E79F', border: '#F4D03F' },
    key:      { emoji: '🔑', label: 'Schlüssel', color: '#F9E79F', border: '#F4D03F' },
    treasure: { emoji: '💰', label: 'Schatz',   color: '#F9E79F', border: '#F4D03F' },
    dragon:   { emoji: '🐉', label: 'Drache',   color: '#27AE60', border: '#1E8449' },
    unicorn:  { emoji: '🦄', label: 'Einhorn',  color: '#D2B4DE', border: '#BB8FCE' },
    ghost:    { emoji: '👻', label: 'Geist',    color: '#F2F4F4', border: '#D5D8DC' },
    alien:    { emoji: '👽', label: 'Alien',    color: '#82E0AA', border: '#58D68D' },
    robot:    { emoji: '🤖', label: 'Roboter',  color: '#AEB6BF', border: '#85929E' },
    potion:   { emoji: '🧪', label: 'Trank',    color: '#AF7AC5', border: '#8E44AD' },
    crystal:  { emoji: '🔮', label: 'Kristall', color: '#D2B4DE', border: '#BB8FCE' },
    egg:      { emoji: '🥚', label: 'Ei',       color: '#FDEBD0', border: '#FAD7A0' },
    nest:     { emoji: '🪺', label: 'Nest',     color: '#D4AC0D', border: '#B7950B' },
    butterfly:{ emoji: '🦋', label: 'Schmetterling', color: '#85C1E9', border: '#5DADE2' },
    bee:      { emoji: '🐝', label: 'Biene',    color: '#F9E79F', border: '#F4D03F' },
    honey:    { emoji: '🍯', label: 'Honig',    color: '#F0B27A', border: '#E59866' },
    apple:    { emoji: '🍎', label: 'Apfel',    color: '#E74C3C', border: '#C0392B' },
    cake:     { emoji: '🎂', label: 'Kuchen',   color: '#F1948A', border: '#E74C3C' },
    music:    { emoji: '🎵', label: 'Musik',    color: '#AF7AC5', border: '#8E44AD' },
    heart:    { emoji: '❤️', label: 'Herz',     color: '#E74C3C', border: '#C0392B' },
    skull:    { emoji: '💀', label: 'Skelett',  color: '#F2F4F4', border: '#D5D8DC' },
    poop:     { emoji: '💩', label: 'Haufen',   color: '#8B6914', border: '#6B4F0A' },
    rocket:   { emoji: '🚀', label: 'Rakete',   color: '#E74C3C', border: '#C0392B' },
    ufo:      { emoji: '🛸', label: 'UFO',      color: '#82E0AA', border: '#58D68D' },
    tornado:  { emoji: '🌪️', label: 'Tornado', color: '#AEB6BF', border: '#85929E' },
    wave:     { emoji: '🌊', label: 'Tsunami',  color: '#2980B9', border: '#1F618D' },
    phoenix:  { emoji: '🔥', label: 'Phönix',   color: '#F39C12', border: '#E67E22' },
    // === INTERNET-NOSTALGIE (90er) ===
    modem:    { emoji: '📠', label: 'Modem',    color: '#C8BFA9', border: '#A89F8C' },
    icq:      { emoji: '🌻', label: 'ICQ',      color: '#4BAF4F', border: '#388E3C' },
    aol:      { emoji: '💿', label: 'AOL',      color: '#0055A4', border: '#003D7A' },
    knochenhandy: { emoji: '🦴', label: 'Knochenhandy', color: '#7F8C8D', border: '#616A6B' },
    nokia:    { emoji: '📱', label: 'Nokia 3210', color: '#2C3E50', border: '#1A252F' },
    snake:    { emoji: '🐍', label: 'Snake',    color: '#27AE60', border: '#1E8449' },
    tetris:   { emoji: '🎮', label: 'Tetris',   color: '#8E44AD', border: '#6C3483' },
    // === HÖHLEN (Oscar Edition) ===
    cave:     { emoji: '🕳️', label: 'Höhle',    color: '#34495E', border: '#1C2833' },
    stalactite: { emoji: '🪨', label: 'Tropfstein', color: '#717D7E', border: '#566573' },
    gem:      { emoji: '💠', label: 'Edelstein', color: '#5DADE2', border: '#2E86C1' },
    // === MUSIK (Werkzeug → Folge → Feld) ===
    instrument: { emoji: '🎻', label: 'Instrument', color: '#8B4513', border: '#6E3B1A' },
    // === MUSIK-GENRES (verhackstückt) ===
    krabbenpunk:    { emoji: '🦀', label: 'Krabbenpunk',    color: '#E74C3C', border: '#C0392B' },
    muschelwave:    { emoji: '🐚', label: 'Muschelwave',    color: '#AED6F1', border: '#85C1E9' },
    tiefseebass:    { emoji: '🫧', label: 'Tiefseebass',    color: '#1A5276', border: '#0E3553' },
    korallenjazz:   { emoji: '🪸', label: 'Korallenjazz',   color: '#F1948A', border: '#E74C3C' },
    perlentechno:   { emoji: '🫧', label: 'Perlentechno',   color: '#D5D8DC', border: '#AEB6BF' },
    graphunk:       { emoji: '📻', label: 'Graphunk',       color: '#6E2C00', border: '#4A1C00' },
    modemcore:      { emoji: '🔊', label: 'Modemcore',      color: '#C0392B', border: '#922B21' },
    einwahltrance:  { emoji: '🌀', label: 'Einwahltrance',  color: '#8E44AD', border: '#6C3483' },
    pixelpop:       { emoji: '👾', label: 'Pixelpop',       color: '#FF69B4', border: '#E0559C' },
    chatroomchill:  { emoji: '💬', label: 'Chatroomchill',  color: '#85C1E9', border: '#5DADE2' },
    palmenhouse:    { emoji: '🌴', label: 'Palmenhouse',    color: '#F39C12', border: '#E67E22' },
    vulkanmetal:    { emoji: '🤘', label: 'Vulkanmetal',    color: '#7B241C', border: '#5B1A13' },
    drachendub:     { emoji: '🔥', label: 'Drachendub',     color: '#1E8449', border: '#145A32' },
    blitzhop:       { emoji: '⚡', label: 'Blitzhop',       color: '#F4D03F', border: '#D4AC0D' },
    phoenixfolk:    { emoji: '🪶', label: 'Phönixfolk',     color: '#E67E22', border: '#CA6F1E' },
};
